# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-scripts-authentication
  labels:
    {{- include "zap.labels" . | nindent 4 }}
binaryData:
  {{- range $path, $d := .Files.Glob "scanner/scripts/authentication/*" }}
  {{ $path | base }}: |-
  {{- $d | toString | b64enc | nindent 4 }}
  {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-scripts-session
  labels:
    {{- include "zap.labels" . | nindent 4 }}
binaryData:
  {{- range $path, $d := .Files.Glob "scanner/scripts/session/*" }}
  {{ $path | base }}: |-
  {{- $d | toString | b64enc | nindent 4 }}
  {{ end }}