# SPDX-FileCopyrightText: 2021 iteratec GmbH
#
# SPDX-License-Identifier: Apache-2.0

version: "3"
services:
  bodgeit:
    image: docker.io/psiinon/bodgeit:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "8080:8080"
    healthcheck:
      interval: 1m
      retries: 3
      test:
        - CMD
        - curl
        - -f
        - http://bodgeit:8080/bodgeit/
      timeout: 10s
  juiceshop:
    image: docker.io/bkimminich/juice-shop:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    healthcheck:
      interval: 1m
      retries: 3
      test:
        - CMD
        - wget
        - --spider
        - http://juiceshop:3000/#/
      timeout: 10s
  petstore:
    image: docker.io/swaggerapi/petstore
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "8000:8080"
    environment: 
       - SWAGGER_BASE_PATH=/v2
       - SWAGGER_HOST=http://localhost:8000
       - SWAGGER_URL=http://localhost:8000
    # healthcheck:
    #   interval: 1m
    #   retries: 3
    #   test:
    #     - CMD
    #     - wget
    #     - --spider
    #     - http://petstore/
    #   timeout: 10s
  zap:
    image: owasp/zap2docker-stable:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "8090:8090"
    links:
      - "bodgeit:bodgeit"
      - "juiceshop:juiceshop"
      - "petstore:petstore"
    depends_on: 
      - "bodgeit"
      - "juiceshop"
      - "petstore"
    volumes: 
      - ./scripts/authentication:/home/zap/.ZAP_D/scripts/scripts/authentication
      - ./scripts/session:/home/zap/.ZAP_D/scripts/scripts/session
    entrypoint:
      - 'zap.sh'
      - '-daemon'
      - '-port'
      - '8090'
      - '-host'
      - '0.0.0.0'
      - '-config'
      - 'api.addrs.addr.name=.*'
      - '-config'
      - 'api.addrs.addr.regex=true'
      - '-config'
      - 'api.disablekey=true'
      - '-addonupdate'
      - '-addoninstall'
      - 'pscanrulesBeta'
      - '-addoninstall'
      - 'ascanrulesBeta'
      - '-addoninstall'
      - 'pscanrulesAlpha'
      - '-addoninstall'
      - 'ascanrulesAlpha'
    healthcheck:
      interval: 1m30s
      retries: 3
      test:
        - CMD
        - curl
        - -f
        - http://zap:8090/UI/core/
      timeout: 10s
